config/routes.rb
Rails.application.routes.draw do
  get 'seasons/:id' => 'seasons#show', as: :season
  get 'divisions/:id' => 'divisions#show', as: :division
  get 'teams/:id' => 'teams#show', as: :team
  get 'organizations' => 'organizations#index', as: :organizations
  get 'organizations/:id' => 'organizations#show', as: :organization

  root 'divisions#default'

  get '/faq', to: 'application#faq'

  get '*unmatched_route', to: 'application#render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :season}
  validates :cms_code, presence: true, uniqueness: { scope: :season}

  validates :season, :presence => true
  belongs_to :season
  scope :default, -> { where(default: true) }
  default_scope { order('name DESC') }
  has_many :teams
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  validates :cms_code, presence: true
  validates :location, presence: true
  validates :start_date, presence: true
  validates :division, presence: true
  validates :home_team, presence: true
  validates :home_team_score, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :away_team, presence: true
  validates :away_team_score, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :division
  belongs_to :home_team, :class_name => 'Team', :foreign_key => 'home_team_id'
  belongs_to :away_team, :class_name => 'Team', :foreign_key => 'away_team_id'

  default_scope { order('date ASC') }

  scope :played, -> { where('home_team_score > 0 or away_team_score > 0') }

  def winner?(team)
    ((home_team == team) && (home_team_score > away_team_score)) ||
      ((away_team == team) && (away_team_score > home_team_score))
  end

  def opponent(team)
    if home_team == team
      away_team
    else
      home_team
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :teams
  validates :name, presence: true, uniqueness: true

  default_scope { order('name') }

  def avg
    if games_count == 0
      0.0
    else
      (wins.to_f/games_count.to_f).round(3)
    end
  end
end

app/models/season.rb
class Season < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :cms_code, presence: true, uniqueness: true

  scope :default, -> { where(default: true) }
  default_scope { order('name DESC') }
  has_many :divisions
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :division}
  validates :cms_code, presence: true, uniqueness: true

  belongs_to :organization
  belongs_to :division
  has_many :home_games, class_name: 'Game', foreign_key: :home_team_id
  has_many :away_games, class_name: 'Game', foreign_key: :away_team_id

  def games
    Game.where("home_team_id = ? OR away_team_id = ?", id, id).order(date: :desc)
  end

  def games_count
    home_games_count + away_games_count
  end

  def points
    3*wins.to_i + ties.to_i
  end

  def wp
    games_played = self.wins + self.losses + self.ties
    games_won = self.wins

    if games_played == 0
      0.0
    else
      (1.0 * games_won) / games_played
    end
  end

  def owp
    cumulative_owp = 0.0

    self.games.played.each do |game|
      opponent = game.opponent(self)
      games_played = 0
      games_won = 0

      opponent.games.each do |opponent_game|
        opponent_opponent = opponent_game.opponent(opponent)

        if opponent_opponent != self
          games_played += 1
          games_won += 1 if opponent_game.winner?(opponent)
        end
      end

      if games_played != 0
        cumulative_owp += (1.0 * games_won) / games_played
      end
    end

    if self.games.played.count == 0
      0.0
    else
      (1.0 * cumulative_owp) / self.games.played.count
    end
  end

  def oowp
    games_played = 0
    games_won = 0

    self.games.played.each do |game|
      opponent = game.opponent(self)

      opponent.games.played.each do |opponent_game|
        opponent_opponent = opponent_game.opponent(opponent)

        if opponent_opponent != self
          games_played += (opponent_opponent.wins + opponent_opponent.losses + opponent_opponent.ties)
          games_won += opponent_opponent.wins
        end
      end
    end

    if games_played == 0
      0
    else
      (1.0 * games_won) / games_played
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError, with: :handle_error
  protect_from_forgery with: :exception
  before_action :load_defaults

  def faq
    render :faq
  end

  def render_404
    respond_to do |format|
      format.html do
        load_defaults
        render :file => "#{Rails.root}/public/404", :status => :not_found
      end
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  private
  def handle_error(ex)
    respond_to do |format|
      format.html do 
        load_defaults
        render :file => "#{Rails.root}/public/500", :status => :internal_server_error
      end
      format.xml  { head :internal_server_error }
      format.any  { head :internal_server_error }
    end
  end

  def load_defaults
    @season = Season.default.first
    @division = @season.divisions.default.first
    @seasons = Season.all
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def default
    if @division
      render :show
    else
      render_404
    end
  end

  def show
    if @division = Division.find_by_id(params[:id])
      @season = @division.season
    end

    if @division
      render :show
    else
      render_404
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
  end

  def show
    if @organization = Organization.find_by_id(params[:id])
      render :show
    else
      render_404
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def show
    if params[:id]
      @season = Season.find_by_id(params[:id])
    end

    if @season
      redirect_to division_url(@season.divisions.default.first || @season.divisions.first)
    else
      render_404
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    if @team = Team.find_by_id(params[:id])
      @division = @team.division
      @season = @division.season
      render :show
    else
      render_404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def opponent(team, game)
    if game.home_team.id == team.id
      game.away_team
    else
      game.home_team
    end
  end

  def goals_for(team, game)
    if game.home_team.id == team.id
      game.home_team_score
    else
      game.away_team_score
    end
  end

  def goals_against(team, game)
    if game.home_team.id == team.id
      game.away_team_score
    else
      game.home_team_score
    end
  end

  def display_start_date(game)
    if game.start_date
      game.start_date.in_time_zone("America/Chicago").strftime("%m-%d-%y %l:%M %p")
    else
      "#{game.date} #{game.time}"
    end
  end

  def display_datetime(datetime)
    datetime.in_time_zone("America/Chicago").strftime("Last updated %A, %b %d %Y %l:%M %p")
  end
end

app/views/application/_division.html.erb
<li role="presentation">
<%= link_to division.name, division_path(division), role: "menuitem", tabindex: "-1" %>

app/views/application/_season.html.erb
<li role="presentation">
<%= link_to season.name, season_path(season), role: "menuitem", tabindex: "-1" %>

app/views/application/faq.html.erb
<% content_for :js_postscript do %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#game_locations').dataTable({
        paging:   false,
        info: false,
        searching: false,
        "order": [[ 1, "desc" ]]
    } );
  } );
</script>
<% end %>

<h4>Frequently Asked Questions</h4>
<dl>
  <dt><p>Who has won the most games?</p></dt>
  <dd><p>See the organization breakdown <%= link_to "here", organizations_url %></p></dd>
  <dt>What does RPI mean?</dt>
  <dd><p>RPI (Ratings Percentage Index) is a formula used to rank teams. Traditionally, it has been defined as follows: 
<blockquote>
RPI = 0.25 * WP + 0.50 * OWP + 0.25 * OOWP
</blockquote>

<p>
Here is an example schedule for 4 teams named A, B, C, D: 
<table class="table table-bordered table-condensed" style="width:50%">
    <tr>
      <th></th><th>A</th><th>B</th><th>C</th><td>D</th>
    </tr>
    <tr>
      <th>A</th>
      <td>.</td>
      <td>1</td>
      <td>1</td>
      <td>.</td>
    </tr>
    <tr>
      <th>B</th>
      <td>0</td>
      <td>.</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>C</th>
      <td>0</td>
      <td>1</td>
      <td>.</td>
      <td>1</td>
    </tr>
    <tr>
      <th>D</th>
      <td>.</td>
      <td>1</td>
      <td>0</td>
      <td>.</td>
    </tr>
  </table>
<ul>
<li>1 = win for team in row</li>
<li>0 = loss for team in row</li>
<li>. = not played</li>
</ul>

Each 1 in a team's row represents a win, and each 0 represents a loss. So team C has wins against B and D, and a loss against A. Team A has wins against B and C, but has not played D. 
</p>
WP, OWP, and OOWP are defined for each team as follows: 
<ul>
<li><strong>WP</strong> (Winning Percentage) is the fraction of a teams games that they have won.</li>
<li><strong>OWP</strong> (Opponents' Winning Percentage) is the average WP of a team's opponents, after first throwing out the games they have played against each other.  For example, if you throw out games played against team D, then team B has WP = 0 and team C has WP = 0.5. Therefore team D has OWP = 0.5 * (0 + 0.5) = 0.25. Similarly, team A has OWP = 0.5, team B has OWP = 0.5, and team C has OWP = 2/3.</li>
<li><strong>OOWP</strong> (Opponents' Opponents' Winning Percentage) is the average OWP of a team's opponents. OWP is exactly the number computed in the previous step.  For example, team A has OOWP = 0.5 * (0.5 + 2/3) = 7/12.</li>
</ul> 

Putting it all together, team A has `RPI = (0.25 * 1) + (0.5 * 0.5) + (0.25 * 7 / 12) = 0.6458333...` </p></dd>
  <dt>Why do ties count as a loss?</dt>
  <dd><p>A tie isn't a win.</p></dd>
  <dt>How did you get this data?</dt>
  <dd><p>I used the APIs available at <a href='http://leagueathletics.com/Help/api.shtml'>http://leagueathletics.com/Help/api.shtml</a></p></dd>
  <dt>Where is the site hosted?</dt>
  <dd><p>In the cloud at <a href='https://heroku.com'>Heroku</a>.</p></dd>
  <dt>Where is the source code?</dt>
  <dd><p>The project source is hosted at <a href='https://github.com/brianroth/mnlaxpower'>https://github.com/brianroth/mnlaxpower</a>.</p></dd>
  <dt>What was the largest goal differential ever?</dt>
  <dd><p>The largest goal differential occured on Saturday, August 3 2013 when Hastings defeated Anoka-Ramsey 66-3.  This is probably a data error that should be ignored.</p><p>The second largest goal differential occured on Thursday, July 10 2008 when Mendota Heights defeated Cottage grove 26-0.</p></dd>
  <dt><p>How many games have been played?</p></dt>
  <dd><p>Of the 4428 games played since 2006:
  <ul><li>The home team has won 2006 times</li>
  <li>The away team has won 1737 times</li>
  <li>There have been 685 tie games (or games where the score was 0-0)</li>
  </ul></p></dd>
  <dt><p>How many teams?</p></dt>
  <dd><p>There have been 2299 teams.  However, 1524 never played a game.  This is most likely due to cancelled or incorrect registrations and because at the time this was written, the 2016 schedule hadn't been loaded.</p></dd>
  <dt><p>Where have the most games been played?</p></dt>
  <dd><p>The most common loction for games are:
<div class="table-responsive">
  <table id="game_locations" class="display compact">
  <thead><tr><th>Location</th><th>Games</th></tr></thead>
  <tr><td>Oak-Land JHS</td><td>130</td></tr>
  <tr><td>Chan Pract Turf</td><td>107</td></tr>
  <tr><td>Stonemill Farms</td><td>103</td></tr>
  <tr><td>Wayzata HS Field C</td><td>85</td></tr>
  <tr><td>Wood Park</td><td>84</td></tr>
  <tr><td>Elm Creek Elementary</td><td>83</td></tr>
  <tr><td>Centennial MS Track</td><td>82</td></tr>
  <tr><td>Staring Lake</td><td>81</td></tr>
  <tr><td>Prairie Knoll</td><td>79</td></tr>
  <tr><td>River Crest Elem</td><td>74</td></tr>
  <tr><td>Minnetonka HS Turf</td><td>73</td></tr>
  </table></p></dd>
</dl>

app/views/divisions/_team.html.erb
    <tr>
      <td><%= link_to team.name, team_path(team) %></td>
      <td><%= team.wins %></td>
      <td><%= team.losses %></td>
      <td><%= team.ties %></td>
      <td><%= team.rpi.round(3) %></td>
    </tr>

app/views/divisions/show.html.erb
<% content_for :head do %>
  <title>Minnesota Youth Lacrosse Relative Power Index - <%= @division.name%></title>
<% end %>
<% content_for :js_postscript do %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#division').dataTable({
        paging:   false,
        info: false,
        searching: false,
        "order": [[ 4, "desc" ]]
    } );
  } );
</script>
<% end %>
<div class="row">
  <div class="table-responsive">
    <table id="division" class="display compact">
      <thead>
      <tr>
        <th>Name</th>
        <th>W</th>
        <th>L</th>
        <th>T</th>
        <th>RPI</th>
      </tr>
      </thead>
      <%= render partial: "team", collection: @division.teams %>
    </table>
    <footer>
      <medium class="text-muted"><p><%= display_datetime(@division.updated_at) %></p></medium>
    </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!--<base target="_self">--><base href="." target="_self">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Minnesota youth lacrosse relative power index rankings." />
  <meta name="googlebot" content="index,nofollow" />
  <meta name="robots" content="index,nofollow" />
  <link rel="shortcut icon" href="/mnlaxpower.png">
  <!--stylesheets / link tags loaded here-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/dt/dt-1.10.11/datatables.min.css"/>
 
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-dark bg-primary">
    <button class="navbar-toggler hidden-sm-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        ☰
    </button>
    <a class="navbar-brand" href="/">LAX Relative Power Index</a>
    <div class="collapse navbar-toggleable-xs" id="collapsingNavbar">
        <ul class="nav navbar-nav pull-right">
            <li class="dropdown nav-item active">
          <a id="drop_season" href="#" class="navbar-brand dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= @season.name %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="drop_season">
            <%= render partial: "season", collection: @seasons %>
          </ul>
        </li>
            <li class="dropdown nav-item">
                          <a id="drop_division" href="#" class="navbar-brand dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= @division.name %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="drop_division">
<%= render partial: "division", collection: @season.divisions %>
          </ul>
        </li>
            <li class="nav-item">
                <a class="navbar-brand" href="/faq">F.A.Q.</a>
            </li>
        </ul>
    </div>
</nav>       
<div class="container">
  <%= yield %>
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/t/dt/dt-1.10.11/datatables.min.js"></script>
  <script>
  $(document).ready(function() {
    $('[data-toggle=offcanvas]').click(function() {
        $('.row-offcanvas').toggleClass('active');
    });  
    });
  </script>
<%= yield :js_postscript %>
</body>
</html>

app/views/organizations/_organization.html.erb
<tr>
  <td><%= link_to organization.name, organization_path(organization) %></td>
  <td><%= organization.teams_count %></td>
  <td><%= organization.games_count %></td>
  <td><%= organization.wins %></td>
  <td><%= organization.avg %></td>
</tr>

app/views/organizations/_team.html.erb
    <tr>
      <td><%= link_to team.division.season.name, season_path(team.division.season) %></td>
      <td><%= link_to team.name, team_path(team) %></td>
      <td><%= team.games_count %></td>
      <td><%= team.wins %></td>
    </tr>

app/views/organizations/index.html.erb
<% content_for :head do %>
  <title>Minnesota Youth Lacrosse Relative Power Index</title>
<% end %>
<% content_for :js_postscript do %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#organizations').dataTable({
        paging:   false,
        info: false,
        searching: false,
        "order": [[ 0, "asc" ]]
    } );
  } );
</script>
<% end %>
<div class="table-responsive">
  <table id="organizations" class="display compact">
    <thead>
    <tr>
      <th>Name</th>
      <th>Teams</th>
      <th>Games</th>
      <th>Won</th>
      <th>Avg</th>
    </tr>
    </thead>
    <%= render partial: "organization", collection: @organizations %>
  </table>
</div>

app/views/organizations/show.html.erb
<% content_for :head do %>
  <title>Minnesota Youth Lacrosse Relative Power Index - <%= @organization.name%></title>
<% end %>
<% content_for :js_postscript do %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $('#organization').dataTable({
        paging: false,
        info: false,
        searching: false,
        "order": [[ 0, "asc" ]]
    } );
  } );
</script>
<% end %>
<ol class="breadcrumb">
  <li><%= link_to 'All Organizations', organizations_path() %></li>
  <li class="active"><%= @organization.name %></li>
</ol>

<div class="table-responsive">
  <table id="organization" class="display compact">
    <thead>
    <tr>
      <th>Season</th>
      <th>Name</th>
      <th>Games</th>
      <th>Wins</th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: "team", collection: @organization.teams %>
    </tbody>
  </table>
</div>